// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestService.Models;

#nullable disable

namespace TestService.Migrations
{
    [DbContext(typeof(QuestionContext))]
    [Migration("20231218190143_initial create")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TestService.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"), 1L, 1);

                    b.Property<string>("Answer1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnswerRight")
                        .HasColumnType("int");

                    b.Property<string>("TextQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Answer1 = "усидч..вый, переменч..вый",
                            Answer2 = "отстёг..вавший, глянц..вый",
                            Answer3 = "щегол..ватый, находч..вый",
                            Answer4 = "прислуш..ваться, гор..вать",
                            AnswerRight = 0,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 2,
                            Answer1 = " неразборч..вый, овлад..вать",
                            Answer2 = "высме..вающий, отапл..вать",
                            Answer3 = "запечатл..вать, милост..вый",
                            Answer4 = "завистл..вый, коч..вать",
                            AnswerRight = 1,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 3,
                            Answer1 = "претерп..вающий, замш..вый",
                            Answer2 = "леле..вший, извил..на",
                            Answer3 = "милост..вый, измуч..нный",
                            Answer4 = "разбрызг..вая, тюл..вый",
                            AnswerRight = 0,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 4,
                            Answer1 = "податл..вый; нул..вой",
                            Answer2 = "се..вший, перекле..вать",
                            Answer3 = "кро..тся (тайна), потч..вать",
                            Answer4 = " выздоров..ть, смекал..стый",
                            AnswerRight = 2,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 5,
                            Answer1 = "отво..вав, плать..це",
                            Answer2 = " локт..вой, ключ..к",
                            Answer3 = "угр..ватый, досто..н",
                            Answer4 = "дешев..нький, баш..нка",
                            AnswerRight = 3,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 6,
                            Answer1 = "усидч..вый, зелён..нький",
                            Answer2 = "отстёг..вавший, сем..ни",
                            Answer3 = "находч..вый, страдал..ц",
                            Answer4 = "щегол..ватый, тёт..нька",
                            AnswerRight = 3,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 7,
                            Answer1 = "отта..в, ореш..к",
                            Answer2 = "вкрадч..вый, меньш..нство",
                            Answer3 = "алюмини..вый, пород..стый",
                            Answer4 = " задумч..вый, гир..вой (спорт)",
                            AnswerRight = 1,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 8,
                            Answer1 = "устра..вать, бараш..к",
                            Answer2 = "приукраш..вать, письм..цо",
                            Answer3 = "догадл..вость, крас..вый",
                            Answer4 = "подразум..вающий, луж..ца",
                            AnswerRight = 2,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 9,
                            Answer1 = "з..подозрить, нед..выполнить, п..молчать",
                            Answer2 = "и..быточный, во..хождение, ни..вергнуть",
                            Answer3 = "по..бросить, о..пилить, о..крыть",
                            Answer4 = "пр..мудрый, пр..красный, пр..возмочь",
                            AnswerRight = 3,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 10,
                            Answer1 = " беспр..страстный, пр..вышение (скорости), пр..града",
                            Answer2 = "бе..грамотный, чре..мерный, во..звание",
                            Answer3 = "с..ехидничать, уст..е, в..юга",
                            Answer4 = "неп..ладки, н..вьючить, п..лагать",
                            AnswerRight = 1,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 11,
                            Answer1 = "бе..крайний, ни..вергать, чере..чур",
                            Answer2 = "пр..одолевать, пр..даточный, (негде) пр..моститься",
                            Answer3 = "вз..браться, пр..махнуться, п..ложиться",
                            Answer4 = "в..юнок, в..едливый, двух..ярусный",
                            AnswerRight = 2,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 12,
                            Answer1 = "пр..обрёл, пр..образователь, сверх..нтересный",
                            Answer2 = "п..дсказывать, п..никнуть, д..ехать",
                            Answer3 = "и..древле, не..держанный, не..добровать",
                            Answer4 = "оп..знание, нер..створимый, п..йдём",
                            AnswerRight = 1,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 13,
                            Answer1 = "пр..общиться, пр..школьный, пр..встать",
                            Answer2 = "вз..браться, п..забавить, р..ссказ",
                            Answer3 = "ни..вергать, и..черпать, в..дрогнуть",
                            Answer4 = "об..явить, с..ёмка, суб..ект",
                            AnswerRight = 0,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 14,
                            Answer1 = "п..иск, неп..ддающийся, от..двинуть",
                            Answer2 = "ра..бросать, и..пуганный, бе..вольный",
                            Answer3 = "с..еденный, сер..ёзный, ад..ютант",
                            Answer4 = "нап..следок, н..слаждаться, д..браться",
                            AnswerRight = 0,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 15,
                            Answer1 = "пр..бинтовать, пр..морский, пр..бывать (на станцию)",
                            Answer2 = "по..цепленный (вагон), о..гадать, на..кусить",
                            Answer3 = "ра..сеять, в..балтывать, бе..голосый",
                            Answer4 = "без..ндукционный, меж..гровой, с..мпровизировать",
                            AnswerRight = 0,
                            TextQuestion = "Укажите ответ, в котором в обоих словах одного ряда пропущена одна и та же буква."
                        },
                        new
                        {
                            QuestionId = 16,
                            Answer1 = "Это был (НЕ)КТО иной, как мой друг Борька.",
                            Answer2 = "Щёки у неё были круглые и красные, а губы (НЕ)ЕСТЕСТВЕННО алые.",
                            Answer3 = "Было совершенно (НЕ)ЯСНО, почему они так долго смотрят на этот простой рисунок.",
                            Answer4 = "Почему-то нас он сразу (НЕ)ВЗЛЮБИЛ.",
                            AnswerRight = 0,
                            TextQuestion = "Укажите ответ, в котором НЕ с выделенным словом пишется РАЗДЕЛЬНО."
                        },
                        new
                        {
                            QuestionId = 17,
                            Answer1 = "Всё это свидетельствует о чрезвычайной доброте его тихого и ничуть (НЕ)ЗЛОПАМЯТНОГО сердца.",
                            Answer2 = "Оставив чай (НЕ)ДОПИТЫМ, Макар быстро собрался и пошёл в тайгу.",
                            Answer3 = "Оля что-то всё время (НЕ)ДОГОВАРИВАЛА нам, скрывала.",
                            Answer4 = "Он был человеком самостоятельным, абсолютно ни от кого (НЕ)ЗАВИСЯЩИМ.",
                            AnswerRight = 0,
                            TextQuestion = "Укажите ответ, в котором НЕ с выделенным словом пишется РАЗДЕЛЬНО."
                        },
                        new
                        {
                            QuestionId = 18,
                            Answer1 = "(НА)ВЕРХУ великолепных палат сидел Атлант и держал на плечах небо (В)ВИДЕ шара, который был осыпан рубинами.",
                            Answer2 = "Снег под напором ветра летел (НА)ВСТРЕЧУ (В)ДОЛЬ улицы.",
                            Answer3 = "«Поезжай к князю Петру Ивановичу и подробно узнай, что и как»,  — сказал он одному из адъютантов и (В)СЛЕД (ЗА)ТЕМ обратился к принцу Виртембергскому.",
                            Answer4 = "(НА)ПРОТЯЖЕНИИ всего дня дети играли на лужайке, взрослые ТАК(ЖЕ) были во дворе.",
                            AnswerRight = 1,
                            TextQuestion = "Укажите ответ, в котором все выделенные слова пишутся СЛИТНО."
                        },
                        new
                        {
                            QuestionId = 19,
                            Answer1 = "Катя (С)НАЧАЛА решила посоветоваться с мамой и спросила, ЧТО(БЫ) та сделала на месте Кати.",
                            Answer2 = "Ночью полил такой сильный дождь, что мы все промокли (НА)СКВОЗЬ, но пробраться в деревню (ПО)ПРЕЖНЕМУ было невозможно.",
                            Answer3 = "Я был согласен с мнением Люси лишь (ОТ)ЧАСТИ, но спорить не стал, потому что (ПО)ПРОСТУ не хотел ссоры.",
                            Answer4 = "(ПО)СРЕДИ комнаты (В)ТЕЧЕНИЕ двадцати лет стоял один и тот же стол, покрытый всё той же кружевной скатертью.",
                            AnswerRight = 2,
                            TextQuestion = "Укажите ответ, в котором все выделенные слова пишутся СЛИТНО."
                        },
                        new
                        {
                            QuestionId = 20,
                            Answer1 = "В ТОТ(ЖЕ) день, когда Базаров в саду объяснял Аркадию, (ПО)ЧЕМУ не принялись молодые дубки, он познакомился с Фенечкой.",
                            Answer2 = "Но мне ТАК(ЖЕ) кажется, что Лежнёв не стал бы говорить (ПО)ПУСТУ, не взвесив то, что говорит.",
                            Answer3 = "Мы (ПО)ДОЛГУ сидели на берегу (В)ОБНИМКУ, молчали и слушали прибой.",
                            Answer4 = "Перед выездом Олег решил ВСЁ(ТАКИ) сообщить родителям о своём скором прибытии, дабы не застать их (В)РАСПЛОХ.",
                            AnswerRight = 1,
                            TextQuestion = "Укажите ответ, в котором все выделенные слова пишутся СЛИТНО."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
